AWSTemplateFormatVersion: 2010-09-09

Description: |
  The AWS Cloudformation template for creating CodeBuild execution role.
  This role is passed to cloudformation service by Cross Account Role. 

Parameters:
  ToolsAccountID:
    Description: Account ID of the TOOLS AWS Account that initiates code deployments to this account.
    Type: String
    ConstraintDescription: Must be a valid AWS Account ID without hyphens.
    AllowedPattern: '\d{12}'
    #MinLength: 12
    #MaxLenght: 12
  Stage:
    Description: Stage of the account we are deploying to.
    Type: String
    AllowedValues:
      - Dev
  KeyArn:
    Description: Provide the KMS key ARN if you've deployed the pipeline stack
    Type: String
    ConstraintDescription: Must be a valid AWS ARN for a KMS Key in the TOOLS account
    Default: ''

# If the Key Arn is blank, it's our initial deployment,
# so don't deploy de policy which references the bucket and key
Conditions:
  DeployPolicy: !Not [!Equals [!Ref KeyArn, '']]

Resources:
  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationDeploymentRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
  
  CloudFormationDeploymentPolicy:
    Condition: DeployPolicy
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows pipeline in TOOLS account
      ManagedPolicyName: CloudFormationDeploymentPolicy
      Roles:
        - !Ref CloudFormationDeploymentRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: iam:PassRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/*
            Effect: Allow
          - Action:
              - iam:Get*
              - iam:*Role*
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:CreateServiceLinkedRole
              - iam:DeleteServiceLinkedRole
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:*PolicyVersion*
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/*
            Effect: Allow
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::artifact-bucket-${ToolsAccountID}
              - !Sub arn:aws:s3:::artifact-bucket-${ToolsAccountID}/*
            Effect: Allow
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: !Sub ${KeyArn}
            Effect: Allow
          - Action:
              - cloudformation:CreateStack
              - cloudformation:DescribeStack*
              - cloudformation:GetStackPolicy
              - cloudformation:GetTemplate*
              - cloudformation:SetStackPolicy
              - cloudformation:UpdateStack
              - cloudformation:ValidateTemplate
            Resource: !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/${Stage}ApplicationDeploymentStack/*
            Effect: Allow